language: r
r: bioc-release
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- ./_build.sh
- ./_deploy.sh
sudo: true
cache:
  packages: true
  directories:
  - $TRAVIS_BUILD_DIR/_bookdown_files
env:
  global:
  - secure: Y7DgFfLiBV51pBuCQxXhMZ7QUSb6kRbmqJQSCaXGosxMLCLQkuFWOcyJ4ltrzps9Tz+XButTIYmG4qhUte+T1sEu63PcqoC95lcR9hkumrbSzDRh61acFIvdaBeCE/kwrelMF5HvhoFeP9DZ0KhJsLZokKXIqkWNtf4jJARD1BLZHlXRS9mwXUumAhAC3Z+KyFlnWrHWg4Po3K/J138+3DUdtMHcb+HkqH0BRmhvwIBluCfGxnOLcZHwHJ260Rj6Y62NyjNEQkc1fjsYnQA+4bYMEPCX6sn3H3etxNp6waySpbaQkBSGzm9AlScaUje/hLxVfOA++AmoweUfnrmrWmLShILdfqbORZKLqqfBbl1MWEivOaU0WJRJ++JGLcu/OSZhT9yJF4TsUyv6RWodNLf4HibDYJ2DyQW3eIoHnrbMNe8I8/pbhx/ssEAPsR5oI0xHh7rn8dTdP+TwgZlu5WHgmR9f4NviGTXrm9WDgJh8pUHTFXm+jUbclKfM8GlPPp42gFY3GGXeX06/OK4UWDZl1jNrB2dgsVFYHzdb6IlQMWiO0HQq15AazhRRy522fIX1/8jkySD5jZyBjyAQ+QyssGhf9X3xuNzqK1kl5OVfKCKz1Oeep2gqRjxS8gqEJrgwVt3XInYj8A7G7obBcNqtuTHq0e4wip9I8XAW5xI=
