language: r
r: bioc-release
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- ./_build.sh
- ./_deploy.sh
sudo: true
cache:
  packages: true
  directories:
  - $TRAVIS_BUILD_DIR/_bookdown_files
env:
  global:
  - secure: GAaT36dFNUcHKDpP8ucyV8hRHwtrN7lvRXU1Szfyni5jCdzhCJhf3xJbbKUKtZUV5fl5o3xyNs/1zOlkwS51e8IRAkVKEMTV8cYi5ayhpDF9QEdH+Wu9Exn/RyVtCBP4sprynfjhsQi9ox16MNIwUHXtscckegdgOZD62of4x/zpJ/dj7meAoXQSj16lk/TG0r0bBDVnr8/WGqRhWc+V1T9V1cKbznXH7303nMQtR2PaROLVbgBAIw685njWPZEHufzcfw2vp+J7v7BceG4lFDJnC3M+6NJ1teICSjg2I/4r06uL+LCqFd5zuzjFmQsXZgEUa7A/RZ/PYPUY6wiHjhV+2Dt6ctReT6LIsFF7C0niJoRotdNESduS1kNf6STB/nDIkOIycImr6M1+9hBFjUiUZALyXUXm3/2ipSNuOYoeVzWcO10WKZv0utjChHNhg+KXJ58KTtzPVWFQAnNSMU1n9zYkvPGTD+2C8elOpefLK7dyXq4ktkArN+B0EdQ8ta236KN/4lCI5goURJnZPqbpFT/wYiTrJyj4vuX0GV9bn/8/tOAGZ2rz4EVchZcCSzVFVieMNsz6qTVmo9PX+djU1YJWHgde9sZDjSPqDE4g6qNWe450S/09ZZWmfZRf04rTdyeoFRSjL7GuikV9x8LFgfC5EXrWZUb9Cbvz6ak=
